# Generated by Django 4.2.7 on 2025-10-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
